name: matterhorn
base: core18
adopt-info: matterhorn
summary: Matterhorn
description: |
  A feature-rich Unix terminal client for the Mattermost chat system
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  matterhorn:
    command: matterhorn
    plugs:
      - home
      - desktop
      - network
      - password-manager-service
      - x11

parts:
  matterhorn:
    plugin: nil
    override-build: |
      set -eu
      ARCHITECTURE=$(dpkg --print-architecture)
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/matterhorn-chat/matterhorn/releases -O releases.json
      VERSION=$(jq -r '[.[].tag_name][0]' releases.json)
      TAR_URL=$(jq -r '[.[].assets[] | select(.name | contains("ubuntu")) | select(.name | contains(".tar.")).browser_download_url ][0]' releases.json)
      TAR=$(basename "${TAR_URL}")
      echo "Downloading ${TAR_URL}..."
      wget "${TAR_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${TAR}"
      echo "Unpacking ${TAR}..."
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/app"
      tar jxvf "${SNAPCRAFT_PART_INSTALL}/${TAR}" -C "${SNAPCRAFT_PART_INSTALL}/app" --strip-components=1
      for p in "$PWD"/patches/*; do
        (cd "${SNAPCRAFT_PART_INSTALL}/app" && patch -p1 < $p)
      done
      install -m 755 launcher -D ${SNAPCRAFT_PART_INSTALL}/bin/matterhorn -v
      rm -f releases.json
      rm -f "${SNAPCRAFT_PART_INSTALL}/${TAR}"
      snapcraftctl set-version "$VERSION"
    source: .
    build-packages:
      - wget
      - jq
    stage-packages:
      - aspell
      - libsecret-tools
      - libnotify-bin
      - xclip
      # aspell dictionaries
      - aspell-af
      - aspell-am
      - aspell-ar
      - aspell-ar-large
      - aspell-bg
      - aspell-bn
      - aspell-br
      - aspell-ca
      - aspell-cs
      - aspell-cy
      - aspell-da
      - aspell-de
      - aspell-de-1901
      - aspell-doc
      - aspell-el
      - aspell-en
      - aspell-eo
      - aspell-eo-cx7
      - aspell-es
      - aspell-et
      - aspell-eu
      - aspell-fa
      - aspell-fo
      - aspell-fr
      - aspell-ga
      - aspell-gl-minimos
      - aspell-gu
      - aspell-he
      - aspell-hi
      - aspell-hr
      - aspell-hsb
      - aspell-hu
      - aspell-hy
      - aspell-id
      - aspell-is
      - aspell-it
      - aspell-kk
      - aspell-kn
      - aspell-ku
      - aspell-lt
      - aspell-lv
      - aspell-ml
      - aspell-mr
      - aspell-nl
      - aspell-no
      - aspell-nr
      - aspell-ns
      - aspell-or
      - aspell-pa
      - aspell-pl
      - aspell-pt
      - aspell-pt-br
      - aspell-pt-pt
      - aspell-ro
      - aspell-ru
      - aspell-sk
      - aspell-sl
      - aspell-ss
      - aspell-st
      - aspell-sv
      - aspell-ta
      - aspell-te
      - aspell-tl
      - aspell-tn
      - aspell-ts
      - aspell-uk
      - aspell-uz
      - aspell-xh
      - aspell-zu

