name: matterhorn
base: core18
adopt-info: matterhorn
summary: Matterhorn
description: |
  A feature-rich Unix terminal client for the Mattermost chat system
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  matterhorn:
    command: matterhorn
    plugs:
      - home
      - desktop
      - network
      - password-manager-service

parts:
  matterhorn:
    plugin: nil
    override-build: |
      set -eu
      ARCHITECTURE=$(dpkg --print-architecture)
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/matterhorn-chat/matterhorn/releases -O releases.json
      VERSION=$(jq -r '[.[].tag_name][0]' releases.json)
      TAR_URL=$(jq -r '[.[].assets[] | select(.name | contains("ubuntu")) | select(.name | contains(".tar.")).browser_download_url ][0]' releases.json)
      TAR=$(basename "${TAR_URL}")
      echo "Downloading ${TAR_URL}..."
      wget "${TAR_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${TAR}"
      echo "Unpacking ${TAR}..."
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/app"
      tar jxvf "${SNAPCRAFT_PART_INSTALL}/${TAR}" -C "${SNAPCRAFT_PART_INSTALL}/app" --strip-components=1
      rm -f releases.json
      rm -f "${SNAPCRAFT_PART_INSTALL}/${TAR}"
      snapcraftctl set-version "$VERSION"
    build-packages:
      - wget
      - jq
    stage-packages:
      - libsecret-tools
      - libnotify-bin
      - xclip

